---
title: "Intro to Quarto"
subtitle: "BSTA 6100 Fall 2025 Lab 00"
author: "Your Name Here"
date: "today"
format:
  html:
    theme: "zephyr"
    toc: true
    embed-resources: true
---

:::{.callout-note}
Materials in this lab are adapted from 
:::


## Quarto

This is a Quarto document. It's written (partially) in a syntax called [Markdown](https://quarto.org/docs/authoring/markdown-basics.html). Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. It was designed to simplify creating HTML documents, but the labs for this text are written to generate HTML documents.
Throughout the course, we'll be using Quarto to prepare lab reports. 

The first lines of this file (between `---`) are referred to as the **header**. Quarto is *very* fussy about the form of the header---the three dashed lines above and below lines 2-9 must appear exactly as in this document, and there must be a blank space between the colon and the descriptive text. Also, the title, author, and date fields must be kept within double quotes. The output line specifies the output format as HTML. You can find other theme options for HTML documents [here](https://bootswatch.com/).

Quarto runs code contained in "chunks". A chunk looks like this:
```{r}
#| label: hello-world

print("Hello world!")

```

Notice that the code, `print("Hello world!")` is contained between three backticks (below the esc key on a US English keyboard, on the same key as the tilde) and the first set of backticks ends with `{r}`. This is how Quarto knows where your chunks start and stop. 

You can run the code inside a single chunk by clicking the green "play" button in the upper right corner of the chunk. It's usually a good idea to click the "Run All Chunks Above" button immediately to the left of the play button first. So you should click Run All Chunks Above, then the play button.

If you can't find the play button, just highlight the code you want to run and click the Run button in the top right corner of the editor pane.

When you click the **Render** button in RStudio, a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. 

You can create a new R code chunk by either typing the three backticks (`) followed by an "r" enclosed in braces, then the additional three backticks to close the chunk, or simply press the *Insert Chunk* button from the *Chunks* menu on the far right of the toolbar on top of the script editor. 

### Tips for Quarto
1. **Render and render often**: Frequently knitting your document will help you make sure that all your code works and that the document looks the way you want. You might even check the "Render on Save" button to help with this. (It's very useful!)
1. **Don't be afraid to experiment**: Nobody gets things exactly right the first time, and we all forget how things work sometimes. Keep trying, and you'll eventually get what you want! Your computer won't explode if you get an error, so don't be afraid!
1. **Use your resources**: Resources like [Quarto's reference manual](https://quarto.org/docs/reference/) and even Google are your friends! You should feel empowered to learn and troubleshoot errors on your own.

The content of a Quarto document is created in the R Studio script editor. Formatting commands in the text are converted to a rendered document when you click on the *Render* button, located on the toolbar at the top of the script editor.

In R Studio, the menu item *File > New File > Quarto Document...* choice produces a dialog box for output type. To create a new document, select *Document* from the left side of the dialog box, enter a name and title, choose HTML, and select OK. A template will open in the script editor, with file extension .qmd. Templates will be provided for all the lab exercises, and you will start by simply opening the template files, so there will almost never be a need to start a new file "from scratch" while working on these labs.

Note that you *can* render to a PDF, but this requires additional software installation that is outside the scope of what we'll discuss in our labs.

### Formatting Basics

Plain text is prepared in paragraphs, as in the first part of this document. *Text* enclosed in asterisks is *italicized* in the PDF output. **Text** enclosed in double asterisks appears in **bold font**. There must be no space between the asterisks and the enclosed text. `Text` enclosed in backticks is formatted as if it's code (but will not be executed!).

Bulleted lists are produced using the formatting syntax: 

- Item 1 
- Item 2 
    + Item 2a
    + Item 2b

The list must be preceded by a blank line, and 4 spaces should be used before sub-items.

<!---
To make a "comment" in an R Markdown document, use the syntax on the lines preceding and following this message. All the text within the 'arrows' does not appear in the rendered document, similar to how lines preceded with a # in R are not executed as code.
--->


Plain text is prepared in paragraphs, as in the first part of this document. *Text* enclosed in asterisks is *italicized* in the PDF output. **Text** enclosed in double asterisks appears in **bold font**.  There must be no space between the asterisks and the enclosed text.

Additional formatting commands will be introduced gradually throughout the rest of the labs.

<!---
To make a "comment" in an R Markdown document, use the syntax on the lines preceding and following this message. All the text within the 'arrows' does not appear in the knitted PDF, similar to how lines preceded with a # in R are not executed as code.
--->


### Using R with R Markdown

The real power of R Markdown is that it allows for R programs to be included in the Rmd file, with both the program and its output automatically being produced in the PDF document.

R programs in an Rmd file are located in **code chunks**, which appear as grey-shaded blocks as shown below starting on line 60. You can embed an R code chunk by either typing the three backticks (`) followed by an "r" enclosed in braces, then the additional three backticks to close the chunk, or simply press the *Insert Chunk* button from the *Chunks* menu on the far right of the toolbar on top of the script editor. 


### R Script versus R Markdown

An R Script file can be thought of as one large code chunk; R script files are only meant to contain R commands with short plain-text comments. R Markdown files consist of both code, output, and plain text.

R script files are useful when the primary goal is to explore a dataset or test short R programs. R Markdown files are ideal for preparing documents that need to contain both explanatory text and statistical output, such as a lab report. 

Congratulations! You have reached the end of Lab 0. 